### ISSUE TITLE
Archiv je neaktualizovaný

### ISSUE THREAD

**Issue by vrana** [ondrejmirtes/ondrej.mirtes.cz#2]
https://ondrej.mirtes.cz/archiv/2014/ ukazuje příspěvek naposledy z března 2013. https://ondrej.mirtes.cz/archiv/ má redirect loop.

**Comment by vrana** [comment]
Aha, ona to je možná feature, ne bug - archiv začíná tam, kde končí homepage. Nicméně se mi to nezdá moc intuitivní.

**Comment by ondrejmirtes** [comment]
Je to tak, nechci mít duplicity mezi homepagí a archivem. Když dojedeš na konec homepage a v patičce dáš "Archiv >", tak chci, abys viděl další články a ne znovu ty samé...
